// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/Daviddochain/dochain-core/v4/types/assets/
// ALIASGEN: github.com/Daviddochain/dochain-core/v4/types/util/
package types

import (
	"github.com/Daviddochain/dochain-core/v4/types/assets"
	"github.com/Daviddochain/dochain-core/v4/types/util"
)

const (
	MicroDoDenom  = assets.MicroDoDenom
	MicroSDRDenom = assets.MicroSDRDenom
	MicroUSDDenom = assets.MicroUSDDenom
	MicroKRWDenom = assets.MicroKRWDenom
	MicroCNYDenom = assets.MicroCNYDenom
	MicroGBPDenom = assets.MicroGBPDenom
	MicroMNTDenom = assets.MicroMNTDenom
	MicroUnit     = assets.MicroUnit

	BlocksPerMinute      = util.BlocksPerMinute
	BlocksPerHour        = util.BlocksPerHour
	BlocksPerDay         = util.BlocksPerDay
	BlocksPerWeek        = util.BlocksPerWeek
	BlocksPerMonth       = util.BlocksPerMonth
	BlocksPerYear        = util.BlocksPerYear
	CoinType             = util.CoinType
	Purpose              = util.Purpose
	Bech32PrefixAccAddr  = util.Bech32PrefixAccAddr
	Bech32PrefixAccPub   = util.Bech32PrefixAccPub
	Bech32PrefixValAddr  = util.Bech32PrefixValAddr
	Bech32PrefixValPub   = util.Bech32PrefixValPub
	Bech32PrefixConsAddr = util.Bech32PrefixConsAddr
	Bech32PrefixConsPub  = util.Bech32PrefixConsPub
	ColumbusChainID      = "cookie-1"
	BombayChainID        = "bombay-12"
	RebelChainID         = "rebel-2"
	OsmoIbcDenom         = "ibc/0ef15df2f02480ade0bb6e85d9ebb5daea2836d3860e9f97f9aade4f57a31aa0"
)

// function aliases
var (
	IsPeriodLastBlock = util.IsPeriodLastBlock
	AddressVerifier   = util.AddressVerifier
)
