// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: do/validatorrewards/v1beta1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryRewardDenomRequest struct {
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
}

func (m *QueryRewardDenomRequest) Reset()         { *m = QueryRewardDenomRequest{} }
func (m *QueryRewardDenomRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRewardDenomRequest) ProtoMessage()    {}
func (*QueryRewardDenomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5374c524abca9252, []int{0}
}
func (m *QueryRewardDenomRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRewardDenomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRewardDenomRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRewardDenomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRewardDenomRequest.Merge(m, src)
}
func (m *QueryRewardDenomRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRewardDenomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRewardDenomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRewardDenomRequest proto.InternalMessageInfo

func (m *QueryRewardDenomRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

type QueryRewardDenomResponse struct {
	RewardDenom *RewardDenom `protobuf:"bytes,1,opt,name=reward_denom,json=rewardDenom,proto3" json:"reward_denom,omitempty"`
}

func (m *QueryRewardDenomResponse) Reset()         { *m = QueryRewardDenomResponse{} }
func (m *QueryRewardDenomResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRewardDenomResponse) ProtoMessage()    {}
func (*QueryRewardDenomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5374c524abca9252, []int{1}
}
func (m *QueryRewardDenomResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRewardDenomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRewardDenomResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRewardDenomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRewardDenomResponse.Merge(m, src)
}
func (m *QueryRewardDenomResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRewardDenomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRewardDenomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRewardDenomResponse proto.InternalMessageInfo

func (m *QueryRewardDenomResponse) GetRewardDenom() *RewardDenom {
	if m != nil {
		return m.RewardDenom
	}
	return nil
}

type QueryRewardDenomsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryRewardDenomsRequest) Reset()         { *m = QueryRewardDenomsRequest{} }
func (m *QueryRewardDenomsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRewardDenomsRequest) ProtoMessage()    {}
func (*QueryRewardDenomsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5374c524abca9252, []int{2}
}
func (m *QueryRewardDenomsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRewardDenomsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRewardDenomsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRewardDenomsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRewardDenomsRequest.Merge(m, src)
}
func (m *QueryRewardDenomsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRewardDenomsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRewardDenomsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRewardDenomsRequest proto.InternalMessageInfo

func (m *QueryRewardDenomsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryRewardDenomsResponse struct {
	RewardDenoms []*RewardDenom      `protobuf:"bytes,1,rep,name=reward_denoms,json=rewardDenoms,proto3" json:"reward_denoms,omitempty"`
	Pagination   *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryRewardDenomsResponse) Reset()         { *m = QueryRewardDenomsResponse{} }
func (m *QueryRewardDenomsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRewardDenomsResponse) ProtoMessage()    {}
func (*QueryRewardDenomsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5374c524abca9252, []int{3}
}
func (m *QueryRewardDenomsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRewardDenomsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRewardDenomsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRewardDenomsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRewardDenomsResponse.Merge(m, src)
}
func (m *QueryRewardDenomsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRewardDenomsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRewardDenomsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRewardDenomsResponse proto.InternalMessageInfo

func (m *QueryRewardDenomsResponse) GetRewardDenoms() []*RewardDenom {
	if m != nil {
		return m.RewardDenoms
	}
	return nil
}

func (m *QueryRewardDenomsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryCampaignRequest struct {
	CampaignId uint64 `protobuf:"varint,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
}

func (m *QueryCampaignRequest) Reset()         { *m = QueryCampaignRequest{} }
func (m *QueryCampaignRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCampaignRequest) ProtoMessage()    {}
func (*QueryCampaignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5374c524abca9252, []int{4}
}
func (m *QueryCampaignRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCampaignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCampaignRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCampaignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCampaignRequest.Merge(m, src)
}
func (m *QueryCampaignRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCampaignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCampaignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCampaignRequest proto.InternalMessageInfo

func (m *QueryCampaignRequest) GetCampaignId() uint64 {
	if m != nil {
		return m.CampaignId
	}
	return 0
}

type QueryCampaignResponse struct {
	Campaign *Campaign `protobuf:"bytes,1,opt,name=campaign,proto3" json:"campaign,omitempty"`
}

func (m *QueryCampaignResponse) Reset()         { *m = QueryCampaignResponse{} }
func (m *QueryCampaignResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCampaignResponse) ProtoMessage()    {}
func (*QueryCampaignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5374c524abca9252, []int{5}
}
func (m *QueryCampaignResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCampaignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCampaignResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCampaignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCampaignResponse.Merge(m, src)
}
func (m *QueryCampaignResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCampaignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCampaignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCampaignResponse proto.InternalMessageInfo

func (m *QueryCampaignResponse) GetCampaign() *Campaign {
	if m != nil {
		return m.Campaign
	}
	return nil
}

type QueryCampaignsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryCampaignsRequest) Reset()         { *m = QueryCampaignsRequest{} }
func (m *QueryCampaignsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCampaignsRequest) ProtoMessage()    {}
func (*QueryCampaignsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5374c524abca9252, []int{6}
}
func (m *QueryCampaignsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCampaignsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCampaignsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCampaignsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCampaignsRequest.Merge(m, src)
}
func (m *QueryCampaignsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCampaignsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCampaignsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCampaignsRequest proto.InternalMessageInfo

func (m *QueryCampaignsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryCampaignsResponse struct {
	Campaigns  []*Campaign         `protobuf:"bytes,1,rep,name=campaigns,proto3" json:"campaigns,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryCampaignsResponse) Reset()         { *m = QueryCampaignsResponse{} }
func (m *QueryCampaignsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCampaignsResponse) ProtoMessage()    {}
func (*QueryCampaignsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5374c524abca9252, []int{7}
}
func (m *QueryCampaignsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCampaignsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCampaignsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCampaignsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCampaignsResponse.Merge(m, src)
}
func (m *QueryCampaignsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCampaignsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCampaignsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCampaignsResponse proto.InternalMessageInfo

func (m *QueryCampaignsResponse) GetCampaigns() []*Campaign {
	if m != nil {
		return m.Campaigns
	}
	return nil
}

func (m *QueryCampaignsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryValidatorCampaignsRequest struct {
	ValidatorAddress string             `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	Pagination       *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryValidatorCampaignsRequest) Reset()         { *m = QueryValidatorCampaignsRequest{} }
func (m *QueryValidatorCampaignsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryValidatorCampaignsRequest) ProtoMessage()    {}
func (*QueryValidatorCampaignsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5374c524abca9252, []int{8}
}
func (m *QueryValidatorCampaignsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryValidatorCampaignsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryValidatorCampaignsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryValidatorCampaignsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidatorCampaignsRequest.Merge(m, src)
}
func (m *QueryValidatorCampaignsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryValidatorCampaignsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidatorCampaignsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidatorCampaignsRequest proto.InternalMessageInfo

func (m *QueryValidatorCampaignsRequest) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

func (m *QueryValidatorCampaignsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryValidatorCampaignsResponse struct {
	Campaigns  []*Campaign         `protobuf:"bytes,1,rep,name=campaigns,proto3" json:"campaigns,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryValidatorCampaignsResponse) Reset()         { *m = QueryValidatorCampaignsResponse{} }
func (m *QueryValidatorCampaignsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryValidatorCampaignsResponse) ProtoMessage()    {}
func (*QueryValidatorCampaignsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5374c524abca9252, []int{9}
}
func (m *QueryValidatorCampaignsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryValidatorCampaignsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryValidatorCampaignsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryValidatorCampaignsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidatorCampaignsResponse.Merge(m, src)
}
func (m *QueryValidatorCampaignsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryValidatorCampaignsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidatorCampaignsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidatorCampaignsResponse proto.InternalMessageInfo

func (m *QueryValidatorCampaignsResponse) GetCampaigns() []*Campaign {
	if m != nil {
		return m.Campaigns
	}
	return nil
}

func (m *QueryValidatorCampaignsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryRewardDenomRequest)(nil), "do.validatorrewards.v1beta1.QueryRewardDenomRequest")
	proto.RegisterType((*QueryRewardDenomResponse)(nil), "do.validatorrewards.v1beta1.QueryRewardDenomResponse")
	proto.RegisterType((*QueryRewardDenomsRequest)(nil), "do.validatorrewards.v1beta1.QueryRewardDenomsRequest")
	proto.RegisterType((*QueryRewardDenomsResponse)(nil), "do.validatorrewards.v1beta1.QueryRewardDenomsResponse")
	proto.RegisterType((*QueryCampaignRequest)(nil), "do.validatorrewards.v1beta1.QueryCampaignRequest")
	proto.RegisterType((*QueryCampaignResponse)(nil), "do.validatorrewards.v1beta1.QueryCampaignResponse")
	proto.RegisterType((*QueryCampaignsRequest)(nil), "do.validatorrewards.v1beta1.QueryCampaignsRequest")
	proto.RegisterType((*QueryCampaignsResponse)(nil), "do.validatorrewards.v1beta1.QueryCampaignsResponse")
	proto.RegisterType((*QueryValidatorCampaignsRequest)(nil), "do.validatorrewards.v1beta1.QueryValidatorCampaignsRequest")
	proto.RegisterType((*QueryValidatorCampaignsResponse)(nil), "do.validatorrewards.v1beta1.QueryValidatorCampaignsResponse")
}

func init() {
	proto.RegisterFile("do/validatorrewards/v1beta1/query.proto", fileDescriptor_5374c524abca9252)
}

var fileDescriptor_5374c524abca9252 = []byte{
	// 596 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0x4d, 0x6b, 0x13, 0x41,
	0x18, 0xee, 0xd4, 0x56, 0x9a, 0x37, 0x11, 0x74, 0xa8, 0x9a, 0xae, 0xb8, 0xad, 0x0b, 0xda, 0x2a,
	0x74, 0x97, 0xa4, 0x55, 0x0f, 0x7a, 0xb0, 0x1f, 0x28, 0x22, 0x8a, 0xae, 0xe0, 0x21, 0x97, 0x30,
	0xc9, 0x0c, 0xdb, 0x05, 0xb3, 0x93, 0xec, 0x6c, 0xa2, 0x15, 0xfc, 0x0d, 0xfa, 0x2b, 0xbc, 0x7a,
	0xd0, 0x83, 0x3f, 0xc1, 0x63, 0xf1, 0xe4, 0x51, 0x92, 0xdf, 0x21, 0x48, 0x76, 0x66, 0x36, 0xdb,
	0x8d, 0x49, 0xdc, 0xd2, 0x83, 0xa7, 0xf0, 0x4e, 0xde, 0xe7, 0xe3, 0x7d, 0xe6, 0x63, 0x61, 0x9d,
	0x72, 0xa7, 0x47, 0x5e, 0xfb, 0x94, 0x44, 0x3c, 0x0c, 0xd9, 0x1b, 0x12, 0x52, 0xe1, 0xf4, 0x2a,
	0x0d, 0x16, 0x91, 0x8a, 0xd3, 0xe9, 0xb2, 0xf0, 0xd0, 0x6e, 0x87, 0x3c, 0xe2, 0xf8, 0x0a, 0xe5,
	0x76, 0xb6, 0xd1, 0x56, 0x8d, 0xc6, 0xad, 0x26, 0x17, 0x2d, 0x2e, 0x9c, 0x06, 0x11, 0x4c, 0xa2,
	0x12, 0x8e, 0x36, 0xf1, 0xfc, 0x80, 0x44, 0x3e, 0x0f, 0x24, 0x91, 0xb1, 0x22, 0x7b, 0xeb, 0x71,
	0xe5, 0xc8, 0x42, 0xfd, 0x75, 0x73, 0x9a, 0x19, 0xad, 0x19, 0xb7, 0x5a, 0x0e, 0x5c, 0x7e, 0x31,
	0xd4, 0x71, 0xe3, 0xd5, 0x7d, 0x16, 0xf0, 0x96, 0xcb, 0x3a, 0x5d, 0x26, 0x22, 0xbc, 0x0c, 0x8b,
	0x74, 0x58, 0x97, 0xd1, 0x1a, 0xda, 0x28, 0xb8, 0xb2, 0xb0, 0x3c, 0x28, 0x8f, 0x03, 0x44, 0x9b,
	0x07, 0x82, 0xe1, 0x27, 0x50, 0x92, 0xec, 0xf5, 0x11, 0xb0, 0x58, 0xdd, 0xb0, 0xa7, 0x8c, 0x6c,
	0xa7, 0x79, 0x8a, 0xe1, 0xa8, 0xb0, 0x1a, 0xe3, 0x42, 0x42, 0x5b, 0x7b, 0x08, 0x30, 0xca, 0x43,
	0xc9, 0xdc, 0xb0, 0x55, 0x06, 0xc3, 0xf0, 0x6c, 0x19, 0xb9, 0x16, 0x79, 0x4e, 0x3c, 0xa6, 0xb0,
	0x6e, 0x0a, 0x69, 0x7d, 0x41, 0xb0, 0xf2, 0x17, 0x11, 0x35, 0xce, 0x53, 0x38, 0x97, 0x1e, 0x47,
	0x94, 0xd1, 0xda, 0x99, 0x5c, 0xf3, 0x94, 0x52, 0xf3, 0x08, 0xfc, 0xe8, 0x98, 0xe9, 0xf9, 0xd8,
	0xf4, 0xfa, 0x4c, 0xd3, 0xd2, 0xcb, 0x31, 0xd7, 0x77, 0x61, 0x39, 0x36, 0xbd, 0x47, 0x5a, 0x6d,
	0xe2, 0x7b, 0x81, 0x4e, 0x65, 0x15, 0x8a, 0x4d, 0xb5, 0x54, 0xf7, 0x69, 0x1c, 0xcb, 0x82, 0x0b,
	0x7a, 0xe9, 0x31, 0xb5, 0x6a, 0x70, 0x31, 0x03, 0x54, 0x93, 0xee, 0xc0, 0x92, 0x6e, 0x53, 0x69,
	0x5e, 0x9f, 0x3a, 0x64, 0x42, 0x90, 0xc0, 0xac, 0x7a, 0x86, 0xfb, 0xd4, 0xf7, 0xea, 0x13, 0x82,
	0x4b, 0x59, 0x05, 0x65, 0x7f, 0x0f, 0x0a, 0xda, 0x87, 0xde, 0xa4, 0x7f, 0xf4, 0x3f, 0xc2, 0x9d,
	0xde, 0xf6, 0x7c, 0x43, 0x60, 0xc6, 0x46, 0x5f, 0x69, 0xf9, 0xb1, 0x4c, 0x9e, 0xc1, 0x85, 0xc4,
	0x5b, 0x9d, 0x50, 0x1a, 0x32, 0x21, 0xe4, 0x35, 0xdb, 0xbd, 0xf6, 0xe3, 0xeb, 0xe6, 0x55, 0xa5,
	0x9a, 0x10, 0xec, 0xc8, 0x96, 0x97, 0x51, 0xe8, 0x07, 0x9e, 0x7b, 0xbe, 0x97, 0x59, 0xcf, 0x64,
	0x3c, 0x7f, 0xe2, 0x8c, 0x3f, 0x23, 0x58, 0x9d, 0x68, 0xfd, 0x7f, 0x0c, 0xbb, 0xfa, 0x7b, 0x01,
	0x16, 0x63, 0xc7, 0xf8, 0x1d, 0x14, 0x53, 0x77, 0x0f, 0x6f, 0x4f, 0xf5, 0x34, 0xe1, 0xcd, 0x33,
	0x6e, 0xe7, 0x44, 0xa9, 0x4c, 0xde, 0x43, 0x29, 0xfd, 0x82, 0xe0, 0x7c, 0x34, 0xfa, 0x58, 0x18,
	0x77, 0xf2, 0xc2, 0x94, 0x7c, 0x07, 0x96, 0x74, 0xc8, 0xb8, 0x32, 0x9b, 0x23, 0xf3, 0x6e, 0x18,
	0xd5, 0x3c, 0x10, 0x25, 0x19, 0x41, 0x21, 0x39, 0x1a, 0x38, 0x07, 0x41, 0x32, 0xeb, 0x56, 0x2e,
	0x8c, 0x52, 0xfd, 0x80, 0x00, 0x8f, 0x1f, 0x4d, 0x7c, 0x6f, 0x36, 0xd7, 0xc4, 0xbb, 0x68, 0xdc,
	0x3f, 0x19, 0x58, 0x3a, 0xda, 0xad, 0x7d, 0xef, 0x9b, 0xe8, 0xa8, 0x6f, 0xa2, 0x5f, 0x7d, 0x13,
	0x7d, 0x1c, 0x98, 0x73, 0x47, 0x03, 0x73, 0xee, 0xe7, 0xc0, 0x9c, 0xab, 0x3d, 0xf0, 0xfc, 0xe8,
	0xa0, 0xdb, 0xb0, 0x9b, 0xbc, 0xe5, 0xec, 0x93, 0x9e, 0x4f, 0x29, 0x6f, 0x1e, 0x10, 0x3f, 0x70,
	0xd4, 0xef, 0x66, 0x93, 0x87, 0xcc, 0xe9, 0x6d, 0x3b, 0x6f, 0xc7, 0xbf, 0xd5, 0xd1, 0x61, 0x9b,
	0x89, 0xc6, 0xd9, 0xf8, 0x13, 0xbd, 0xf5, 0x27, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x88, 0xfb, 0x1c,
	0x5c, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	RewardDenom(ctx context.Context, in *QueryRewardDenomRequest, opts ...grpc.CallOption) (*QueryRewardDenomResponse, error)
	RewardDenoms(ctx context.Context, in *QueryRewardDenomsRequest, opts ...grpc.CallOption) (*QueryRewardDenomsResponse, error)
	Campaign(ctx context.Context, in *QueryCampaignRequest, opts ...grpc.CallOption) (*QueryCampaignResponse, error)
	Campaigns(ctx context.Context, in *QueryCampaignsRequest, opts ...grpc.CallOption) (*QueryCampaignsResponse, error)
	ValidatorCampaigns(ctx context.Context, in *QueryValidatorCampaignsRequest, opts ...grpc.CallOption) (*QueryValidatorCampaignsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) RewardDenom(ctx context.Context, in *QueryRewardDenomRequest, opts ...grpc.CallOption) (*QueryRewardDenomResponse, error) {
	out := new(QueryRewardDenomResponse)
	err := c.cc.Invoke(ctx, "/do.validatorrewards.v1beta1.Query/RewardDenom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RewardDenoms(ctx context.Context, in *QueryRewardDenomsRequest, opts ...grpc.CallOption) (*QueryRewardDenomsResponse, error) {
	out := new(QueryRewardDenomsResponse)
	err := c.cc.Invoke(ctx, "/do.validatorrewards.v1beta1.Query/RewardDenoms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Campaign(ctx context.Context, in *QueryCampaignRequest, opts ...grpc.CallOption) (*QueryCampaignResponse, error) {
	out := new(QueryCampaignResponse)
	err := c.cc.Invoke(ctx, "/do.validatorrewards.v1beta1.Query/Campaign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Campaigns(ctx context.Context, in *QueryCampaignsRequest, opts ...grpc.CallOption) (*QueryCampaignsResponse, error) {
	out := new(QueryCampaignsResponse)
	err := c.cc.Invoke(ctx, "/do.validatorrewards.v1beta1.Query/Campaigns", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ValidatorCampaigns(ctx context.Context, in *QueryValidatorCampaignsRequest, opts ...grpc.CallOption) (*QueryValidatorCampaignsResponse, error) {
	out := new(QueryValidatorCampaignsResponse)
	err := c.cc.Invoke(ctx, "/do.validatorrewards.v1beta1.Query/ValidatorCampaigns", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	RewardDenom(context.Context, *QueryRewardDenomRequest) (*QueryRewardDenomResponse, error)
	RewardDenoms(context.Context, *QueryRewardDenomsRequest) (*QueryRewardDenomsResponse, error)
	Campaign(context.Context, *QueryCampaignRequest) (*QueryCampaignResponse, error)
	Campaigns(context.Context, *QueryCampaignsRequest) (*QueryCampaignsResponse, error)
	ValidatorCampaigns(context.Context, *QueryValidatorCampaignsRequest) (*QueryValidatorCampaignsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) RewardDenom(ctx context.Context, req *QueryRewardDenomRequest) (*QueryRewardDenomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RewardDenom not implemented")
}
func (*UnimplementedQueryServer) RewardDenoms(ctx context.Context, req *QueryRewardDenomsRequest) (*QueryRewardDenomsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RewardDenoms not implemented")
}
func (*UnimplementedQueryServer) Campaign(ctx context.Context, req *QueryCampaignRequest) (*QueryCampaignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Campaign not implemented")
}
func (*UnimplementedQueryServer) Campaigns(ctx context.Context, req *QueryCampaignsRequest) (*QueryCampaignsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Campaigns not implemented")
}
func (*UnimplementedQueryServer) ValidatorCampaigns(ctx context.Context, req *QueryValidatorCampaignsRequest) (*QueryValidatorCampaignsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidatorCampaigns not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_RewardDenom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRewardDenomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RewardDenom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/do.validatorrewards.v1beta1.Query/RewardDenom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RewardDenom(ctx, req.(*QueryRewardDenomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RewardDenoms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRewardDenomsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RewardDenoms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/do.validatorrewards.v1beta1.Query/RewardDenoms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RewardDenoms(ctx, req.(*QueryRewardDenomsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Campaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Campaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/do.validatorrewards.v1beta1.Query/Campaign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Campaign(ctx, req.(*QueryCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Campaigns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCampaignsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Campaigns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/do.validatorrewards.v1beta1.Query/Campaigns",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Campaigns(ctx, req.(*QueryCampaignsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ValidatorCampaigns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryValidatorCampaignsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ValidatorCampaigns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/do.validatorrewards.v1beta1.Query/ValidatorCampaigns",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ValidatorCampaigns(ctx, req.(*QueryValidatorCampaignsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "do.validatorrewards.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RewardDenom",
			Handler:    _Query_RewardDenom_Handler,
		},
		{
			MethodName: "RewardDenoms",
			Handler:    _Query_RewardDenoms_Handler,
		},
		{
			MethodName: "Campaign",
			Handler:    _Query_Campaign_Handler,
		},
		{
			MethodName: "Campaigns",
			Handler:    _Query_Campaigns_Handler,
		},
		{
			MethodName: "ValidatorCampaigns",
			Handler:    _Query_ValidatorCampaigns_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "do/validatorrewards/v1beta1/query.proto",
}

func (m *QueryRewardDenomRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRewardDenomRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRewardDenomRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRewardDenomResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRewardDenomResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRewardDenomResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RewardDenom != nil {
		{
			size, err := m.RewardDenom.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRewardDenomsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRewardDenomsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRewardDenomsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRewardDenomsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRewardDenomsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRewardDenomsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.RewardDenoms) > 0 {
		for iNdEx := len(m.RewardDenoms) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RewardDenoms[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryCampaignRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCampaignRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCampaignRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CampaignId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.CampaignId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryCampaignResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCampaignResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCampaignResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Campaign != nil {
		{
			size, err := m.Campaign.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCampaignsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCampaignsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCampaignsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCampaignsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCampaignsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCampaignsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Campaigns) > 0 {
		for iNdEx := len(m.Campaigns) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Campaigns[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryValidatorCampaignsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryValidatorCampaignsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryValidatorCampaignsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryValidatorCampaignsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryValidatorCampaignsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryValidatorCampaignsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Campaigns) > 0 {
		for iNdEx := len(m.Campaigns) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Campaigns[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryRewardDenomRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRewardDenomResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RewardDenom != nil {
		l = m.RewardDenom.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRewardDenomsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRewardDenomsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.RewardDenoms) > 0 {
		for _, e := range m.RewardDenoms {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCampaignRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CampaignId != 0 {
		n += 1 + sovQuery(uint64(m.CampaignId))
	}
	return n
}

func (m *QueryCampaignResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Campaign != nil {
		l = m.Campaign.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCampaignsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCampaignsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Campaigns) > 0 {
		for _, e := range m.Campaigns {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryValidatorCampaignsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryValidatorCampaignsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Campaigns) > 0 {
		for _, e := range m.Campaigns {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryRewardDenomRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRewardDenomRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRewardDenomRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRewardDenomResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRewardDenomResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRewardDenomResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardDenom", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RewardDenom == nil {
				m.RewardDenom = &RewardDenom{}
			}
			if err := m.RewardDenom.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRewardDenomsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRewardDenomsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRewardDenomsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRewardDenomsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRewardDenomsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRewardDenomsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardDenoms", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardDenoms = append(m.RewardDenoms, &RewardDenom{})
			if err := m.RewardDenoms[len(m.RewardDenoms)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCampaignRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCampaignRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCampaignRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CampaignId", wireType)
			}
			m.CampaignId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CampaignId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCampaignResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCampaignResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCampaignResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Campaign", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Campaign == nil {
				m.Campaign = &Campaign{}
			}
			if err := m.Campaign.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCampaignsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCampaignsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCampaignsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCampaignsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCampaignsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCampaignsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Campaigns", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Campaigns = append(m.Campaigns, &Campaign{})
			if err := m.Campaigns[len(m.Campaigns)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryValidatorCampaignsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryValidatorCampaignsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryValidatorCampaignsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryValidatorCampaignsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryValidatorCampaignsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryValidatorCampaignsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Campaigns", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Campaigns = append(m.Campaigns, &Campaign{})
			if err := m.Campaigns[len(m.Campaigns)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
