// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: do/validatorrewards/v1beta1/rewards.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// RewardDenom records the wallet or governance address allowed to create
// validator reward campaigns for a bank denom.
type RewardDenom struct {
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Admin string `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`
}

func (m *RewardDenom) Reset()         { *m = RewardDenom{} }
func (m *RewardDenom) String() string { return proto.CompactTextString(m) }
func (*RewardDenom) ProtoMessage()    {}
func (*RewardDenom) Descriptor() ([]byte, []int) {
	return fileDescriptor_e37a9764b92e48f5, []int{0}
}
func (m *RewardDenom) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RewardDenom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RewardDenom.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RewardDenom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewardDenom.Merge(m, src)
}
func (m *RewardDenom) XXX_Size() int {
	return m.Size()
}
func (m *RewardDenom) XXX_DiscardUnknown() {
	xxx_messageInfo_RewardDenom.DiscardUnknown(m)
}

var xxx_messageInfo_RewardDenom proto.InternalMessageInfo

func (m *RewardDenom) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *RewardDenom) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

// ValidatorAllocation stores one validator's campaign allocation and released
// amount.
type ValidatorAllocation struct {
	ValidatorAddress string     `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	Amount           types.Coin `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount"`
	Released         string     `protobuf:"bytes,3,opt,name=released,proto3" json:"released,omitempty"`
}

func (m *ValidatorAllocation) Reset()         { *m = ValidatorAllocation{} }
func (m *ValidatorAllocation) String() string { return proto.CompactTextString(m) }
func (*ValidatorAllocation) ProtoMessage()    {}
func (*ValidatorAllocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_e37a9764b92e48f5, []int{1}
}
func (m *ValidatorAllocation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorAllocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorAllocation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorAllocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorAllocation.Merge(m, src)
}
func (m *ValidatorAllocation) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorAllocation) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorAllocation.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorAllocation proto.InternalMessageInfo

func (m *ValidatorAllocation) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

func (m *ValidatorAllocation) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

func (m *ValidatorAllocation) GetReleased() string {
	if m != nil {
		return m.Released
	}
	return ""
}

// Campaign stores a funded validator-delegator reward campaign.
type Campaign struct {
	Id             uint64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Admin          string                `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`
	Denom          string                `protobuf:"bytes,3,opt,name=denom,proto3" json:"denom,omitempty"`
	Title          string                `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Allocations    []ValidatorAllocation `protobuf:"bytes,6,rep,name=allocations,proto3" json:"allocations"`
	StartHeight    int64                 `protobuf:"varint,7,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	EndHeight      int64                 `protobuf:"varint,8,opt,name=end_height,json=endHeight,proto3" json:"end_height,omitempty"`
	DelegatorsOnly bool                  `protobuf:"varint,9,opt,name=delegators_only,json=delegatorsOnly,proto3" json:"delegators_only,omitempty"`
	Cancelled      bool                  `protobuf:"varint,10,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
}

func (m *Campaign) Reset()         { *m = Campaign{} }
func (m *Campaign) String() string { return proto.CompactTextString(m) }
func (*Campaign) ProtoMessage()    {}
func (*Campaign) Descriptor() ([]byte, []int) {
	return fileDescriptor_e37a9764b92e48f5, []int{2}
}
func (m *Campaign) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Campaign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Campaign.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Campaign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Campaign.Merge(m, src)
}
func (m *Campaign) XXX_Size() int {
	return m.Size()
}
func (m *Campaign) XXX_DiscardUnknown() {
	xxx_messageInfo_Campaign.DiscardUnknown(m)
}

var xxx_messageInfo_Campaign proto.InternalMessageInfo

func (m *Campaign) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Campaign) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func (m *Campaign) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *Campaign) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Campaign) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Campaign) GetAllocations() []ValidatorAllocation {
	if m != nil {
		return m.Allocations
	}
	return nil
}

func (m *Campaign) GetStartHeight() int64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

func (m *Campaign) GetEndHeight() int64 {
	if m != nil {
		return m.EndHeight
	}
	return 0
}

func (m *Campaign) GetDelegatorsOnly() bool {
	if m != nil {
		return m.DelegatorsOnly
	}
	return false
}

func (m *Campaign) GetCancelled() bool {
	if m != nil {
		return m.Cancelled
	}
	return false
}

func init() {
	proto.RegisterType((*RewardDenom)(nil), "do.validatorrewards.v1beta1.RewardDenom")
	proto.RegisterType((*ValidatorAllocation)(nil), "do.validatorrewards.v1beta1.ValidatorAllocation")
	proto.RegisterType((*Campaign)(nil), "do.validatorrewards.v1beta1.Campaign")
}

func init() {
	proto.RegisterFile("do/validatorrewards/v1beta1/rewards.proto", fileDescriptor_e37a9764b92e48f5)
}

var fileDescriptor_e37a9764b92e48f5 = []byte{
	// 515 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcd, 0x6e, 0x13, 0x3d,
	0x14, 0xcd, 0xe4, 0xef, 0x4b, 0x3c, 0x9f, 0x0a, 0x98, 0x2c, 0xdc, 0x40, 0x87, 0x34, 0x1b, 0xc2,
	0x22, 0x33, 0xb4, 0x20, 0xb1, 0xa5, 0x69, 0x17, 0xac, 0x40, 0x9a, 0x4a, 0x08, 0x75, 0x13, 0x39,
	0x63, 0x6b, 0x62, 0xc9, 0x63, 0x47, 0xb6, 0x1b, 0xc8, 0x5b, 0xf0, 0x30, 0x5d, 0xf1, 0x04, 0x5d,
	0x56, 0x5d, 0xb1, 0x42, 0x28, 0x79, 0x0c, 0x36, 0x68, 0x6c, 0xe7, 0x87, 0x82, 0x90, 0x58, 0xc5,
	0xe7, 0xdc, 0x73, 0xcf, 0xf5, 0x3d, 0xf1, 0x80, 0x67, 0x44, 0x26, 0x73, 0xcc, 0x19, 0xc1, 0x46,
	0x2a, 0x45, 0x3f, 0x62, 0x45, 0x74, 0x32, 0x3f, 0x9a, 0x50, 0x83, 0x8f, 0x12, 0x8f, 0xe3, 0x99,
	0x92, 0x46, 0xc2, 0x47, 0x44, 0xc6, 0x77, 0xa5, 0xb1, 0x97, 0x76, 0xa3, 0x4c, 0xea, 0x42, 0xea,
	0x64, 0x82, 0x35, 0xdd, 0xf4, 0x67, 0x92, 0x09, 0xd7, 0xdc, 0xdd, 0x77, 0xf5, 0xb1, 0x45, 0x89,
	0x03, 0xbe, 0xd4, 0xc9, 0x65, 0x2e, 0x1d, 0x5f, 0x9e, 0x1c, 0xdb, 0x3f, 0x07, 0x61, 0x6a, 0x67,
	0x9c, 0x51, 0x21, 0x0b, 0xd8, 0x01, 0x0d, 0x52, 0x1e, 0x50, 0xd0, 0x0b, 0x06, 0xed, 0xd4, 0x01,
	0x18, 0x83, 0x06, 0x26, 0x05, 0x13, 0xa8, 0x5a, 0xb2, 0x23, 0x74, 0x7b, 0x35, 0xec, 0x78, 0xef,
	0x13, 0x42, 0x14, 0xd5, 0xfa, 0xdc, 0x28, 0x26, 0xf2, 0xd4, 0xc9, 0xfa, 0x5f, 0x02, 0xf0, 0xf0,
	0xfd, 0x7a, 0x85, 0x13, 0xce, 0x65, 0x86, 0x0d, 0x93, 0x02, 0xbe, 0x05, 0x0f, 0x36, 0x9b, 0x8d,
	0xb1, 0xeb, 0x74, 0x93, 0x46, 0x87, 0xb7, 0x57, 0xc3, 0x03, 0xef, 0xb9, 0x6d, 0xfd, 0xc5, 0xfc,
	0xfe, 0xfc, 0x0e, 0x0f, 0x5f, 0x81, 0x26, 0x2e, 0xe4, 0xa5, 0x30, 0xf6, 0x62, 0xe1, 0xf1, 0x7e,
	0xec, 0x1d, 0xca, 0x78, 0xd6, 0x99, 0xc5, 0xa7, 0x92, 0x89, 0x51, 0xfd, 0xfa, 0xdb, 0x93, 0x4a,
	0xea, 0xe5, 0xb0, 0x0b, 0x5a, 0x8a, 0x72, 0x8a, 0x35, 0x25, 0xa8, 0x66, 0x37, 0xdd, 0xe0, 0xfe,
	0x8f, 0x2a, 0x68, 0x9d, 0xe2, 0x62, 0x86, 0x59, 0x2e, 0xe0, 0x1e, 0xa8, 0x32, 0x62, 0xaf, 0x58,
	0x4f, 0xab, 0x8c, 0xfc, 0x6b, 0x12, 0xdb, 0x3c, 0x6b, 0xbb, 0x79, 0x76, 0x40, 0xc3, 0x30, 0xc3,
	0x29, 0xaa, 0x3b, 0xd6, 0x02, 0xd8, 0x03, 0x21, 0xa1, 0x3a, 0x53, 0x6c, 0x56, 0x86, 0x85, 0x1a,
	0xb6, 0xb6, 0x4b, 0xc1, 0x0f, 0x20, 0xc4, 0x9b, 0x34, 0x35, 0x6a, 0xf6, 0x6a, 0x83, 0xf0, 0xf8,
	0x79, 0xfc, 0x97, 0x07, 0x13, 0xff, 0xe1, 0x6f, 0xf0, 0x59, 0xec, 0x5a, 0xc1, 0x43, 0xf0, 0xbf,
	0x36, 0x58, 0x99, 0xf1, 0x94, 0xb2, 0x7c, 0x6a, 0xd0, 0x7f, 0xbd, 0x60, 0x50, 0x4b, 0x43, 0xcb,
	0xbd, 0xb1, 0x14, 0x3c, 0x00, 0x80, 0x0a, 0xb2, 0x16, 0xb4, 0xac, 0xa0, 0x4d, 0x05, 0xf1, 0xe5,
	0xa7, 0xe0, 0x1e, 0xa1, 0x9c, 0xe6, 0xe5, 0x2c, 0x3d, 0x96, 0x82, 0x2f, 0x50, 0xbb, 0x17, 0x0c,
	0x5a, 0xe9, 0xde, 0x96, 0x7e, 0x27, 0xf8, 0x02, 0x3e, 0x06, 0xed, 0x0c, 0x8b, 0x8c, 0x72, 0x4e,
	0x09, 0x02, 0x56, 0xb2, 0x25, 0x46, 0x17, 0xd7, 0xcb, 0x28, 0xb8, 0x59, 0x46, 0xc1, 0xf7, 0x65,
	0x14, 0x7c, 0x5e, 0x45, 0x95, 0x9b, 0x55, 0x54, 0xf9, 0xba, 0x8a, 0x2a, 0x17, 0xaf, 0x73, 0x66,
	0xa6, 0x97, 0x93, 0x38, 0x93, 0x45, 0x72, 0x86, 0xe7, 0x8c, 0x10, 0x99, 0x4d, 0x31, 0x13, 0x89,
	0xff, 0x1d, 0x66, 0x52, 0xd1, 0x64, 0xfe, 0x32, 0xf9, 0xf4, 0xfb, 0x97, 0x66, 0x16, 0x33, 0xaa,
	0x27, 0x4d, 0xfb, 0xe4, 0x5f, 0xfc, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x29, 0x3d, 0x26, 0x24, 0x8d,
	0x03, 0x00, 0x00,
}

func (m *RewardDenom) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RewardDenom) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RewardDenom) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintRewards(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintRewards(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ValidatorAllocation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorAllocation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorAllocation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Released) > 0 {
		i -= len(m.Released)
		copy(dAtA[i:], m.Released)
		i = encodeVarintRewards(dAtA, i, uint64(len(m.Released)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintRewards(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintRewards(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Campaign) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Campaign) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Campaign) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Cancelled {
		i--
		if m.Cancelled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	if m.DelegatorsOnly {
		i--
		if m.DelegatorsOnly {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if m.EndHeight != 0 {
		i = encodeVarintRewards(dAtA, i, uint64(m.EndHeight))
		i--
		dAtA[i] = 0x40
	}
	if m.StartHeight != 0 {
		i = encodeVarintRewards(dAtA, i, uint64(m.StartHeight))
		i--
		dAtA[i] = 0x38
	}
	if len(m.Allocations) > 0 {
		for iNdEx := len(m.Allocations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Allocations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintRewards(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintRewards(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintRewards(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintRewards(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintRewards(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintRewards(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintRewards(dAtA []byte, offset int, v uint64) int {
	offset -= sovRewards(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RewardDenom) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovRewards(uint64(l))
	}
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovRewards(uint64(l))
	}
	return n
}

func (m *ValidatorAllocation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovRewards(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovRewards(uint64(l))
	l = len(m.Released)
	if l > 0 {
		n += 1 + l + sovRewards(uint64(l))
	}
	return n
}

func (m *Campaign) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovRewards(uint64(m.Id))
	}
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovRewards(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovRewards(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovRewards(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovRewards(uint64(l))
	}
	if len(m.Allocations) > 0 {
		for _, e := range m.Allocations {
			l = e.Size()
			n += 1 + l + sovRewards(uint64(l))
		}
	}
	if m.StartHeight != 0 {
		n += 1 + sovRewards(uint64(m.StartHeight))
	}
	if m.EndHeight != 0 {
		n += 1 + sovRewards(uint64(m.EndHeight))
	}
	if m.DelegatorsOnly {
		n += 2
	}
	if m.Cancelled {
		n += 2
	}
	return n
}

func sovRewards(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRewards(x uint64) (n int) {
	return sovRewards(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RewardDenom) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRewards
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RewardDenom: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RewardDenom: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRewards(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRewards
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValidatorAllocation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRewards
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorAllocation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorAllocation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Released", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Released = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRewards(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRewards
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Campaign) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRewards
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Campaign: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Campaign: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Allocations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Allocations = append(m.Allocations, ValidatorAllocation{})
			if err := m.Allocations[len(m.Allocations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartHeight", wireType)
			}
			m.StartHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndHeight", wireType)
			}
			m.EndHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegatorsOnly", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DelegatorsOnly = bool(v != 0)
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cancelled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Cancelled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipRewards(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRewards
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRewards(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRewards
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRewards
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRewards
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRewards
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRewards        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRewards          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRewards = fmt.Errorf("proto: unexpected end of group")
)
