// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: do/validatorrewards/v1beta1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRegisterRewardDenom struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Denom     string `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	Admin     string `protobuf:"bytes,3,opt,name=admin,proto3" json:"admin,omitempty"`
}

func (m *MsgRegisterRewardDenom) Reset()         { *m = MsgRegisterRewardDenom{} }
func (m *MsgRegisterRewardDenom) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterRewardDenom) ProtoMessage()    {}
func (*MsgRegisterRewardDenom) Descriptor() ([]byte, []int) {
	return fileDescriptor_1130ead32fd7b82c, []int{0}
}
func (m *MsgRegisterRewardDenom) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterRewardDenom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterRewardDenom.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterRewardDenom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterRewardDenom.Merge(m, src)
}
func (m *MsgRegisterRewardDenom) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterRewardDenom) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterRewardDenom.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterRewardDenom proto.InternalMessageInfo

type MsgRegisterRewardDenomResponse struct {
}

func (m *MsgRegisterRewardDenomResponse) Reset()         { *m = MsgRegisterRewardDenomResponse{} }
func (m *MsgRegisterRewardDenomResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterRewardDenomResponse) ProtoMessage()    {}
func (*MsgRegisterRewardDenomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1130ead32fd7b82c, []int{1}
}
func (m *MsgRegisterRewardDenomResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterRewardDenomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterRewardDenomResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterRewardDenomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterRewardDenomResponse.Merge(m, src)
}
func (m *MsgRegisterRewardDenomResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterRewardDenomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterRewardDenomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterRewardDenomResponse proto.InternalMessageInfo

type MsgCreateCampaign struct {
	Admin          string                `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	Denom          string                `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	Title          string                `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Allocations    []ValidatorAllocation `protobuf:"bytes,5,rep,name=allocations,proto3" json:"allocations"`
	StartHeight    int64                 `protobuf:"varint,6,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	EndHeight      int64                 `protobuf:"varint,7,opt,name=end_height,json=endHeight,proto3" json:"end_height,omitempty"`
	DelegatorsOnly bool                  `protobuf:"varint,8,opt,name=delegators_only,json=delegatorsOnly,proto3" json:"delegators_only,omitempty"`
}

func (m *MsgCreateCampaign) Reset()         { *m = MsgCreateCampaign{} }
func (m *MsgCreateCampaign) String() string { return proto.CompactTextString(m) }
func (*MsgCreateCampaign) ProtoMessage()    {}
func (*MsgCreateCampaign) Descriptor() ([]byte, []int) {
	return fileDescriptor_1130ead32fd7b82c, []int{2}
}
func (m *MsgCreateCampaign) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateCampaign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateCampaign.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateCampaign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateCampaign.Merge(m, src)
}
func (m *MsgCreateCampaign) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateCampaign) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateCampaign.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateCampaign proto.InternalMessageInfo

type MsgCreateCampaignResponse struct {
	CampaignId uint64 `protobuf:"varint,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
}

func (m *MsgCreateCampaignResponse) Reset()         { *m = MsgCreateCampaignResponse{} }
func (m *MsgCreateCampaignResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateCampaignResponse) ProtoMessage()    {}
func (*MsgCreateCampaignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1130ead32fd7b82c, []int{3}
}
func (m *MsgCreateCampaignResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateCampaignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateCampaignResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateCampaignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateCampaignResponse.Merge(m, src)
}
func (m *MsgCreateCampaignResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateCampaignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateCampaignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateCampaignResponse proto.InternalMessageInfo

func (m *MsgCreateCampaignResponse) GetCampaignId() uint64 {
	if m != nil {
		return m.CampaignId
	}
	return 0
}

type MsgReleaseCampaign struct {
	Releaser   string `protobuf:"bytes,1,opt,name=releaser,proto3" json:"releaser,omitempty"`
	CampaignId uint64 `protobuf:"varint,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
}

func (m *MsgReleaseCampaign) Reset()         { *m = MsgReleaseCampaign{} }
func (m *MsgReleaseCampaign) String() string { return proto.CompactTextString(m) }
func (*MsgReleaseCampaign) ProtoMessage()    {}
func (*MsgReleaseCampaign) Descriptor() ([]byte, []int) {
	return fileDescriptor_1130ead32fd7b82c, []int{4}
}
func (m *MsgReleaseCampaign) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgReleaseCampaign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgReleaseCampaign.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgReleaseCampaign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgReleaseCampaign.Merge(m, src)
}
func (m *MsgReleaseCampaign) XXX_Size() int {
	return m.Size()
}
func (m *MsgReleaseCampaign) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgReleaseCampaign.DiscardUnknown(m)
}

var xxx_messageInfo_MsgReleaseCampaign proto.InternalMessageInfo

type MsgReleaseCampaignResponse struct {
	Released []ValidatorAllocation `protobuf:"bytes,1,rep,name=released,proto3" json:"released"`
}

func (m *MsgReleaseCampaignResponse) Reset()         { *m = MsgReleaseCampaignResponse{} }
func (m *MsgReleaseCampaignResponse) String() string { return proto.CompactTextString(m) }
func (*MsgReleaseCampaignResponse) ProtoMessage()    {}
func (*MsgReleaseCampaignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1130ead32fd7b82c, []int{5}
}
func (m *MsgReleaseCampaignResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgReleaseCampaignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgReleaseCampaignResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgReleaseCampaignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgReleaseCampaignResponse.Merge(m, src)
}
func (m *MsgReleaseCampaignResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgReleaseCampaignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgReleaseCampaignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgReleaseCampaignResponse proto.InternalMessageInfo

func (m *MsgReleaseCampaignResponse) GetReleased() []ValidatorAllocation {
	if m != nil {
		return m.Released
	}
	return nil
}

type MsgCancelCampaign struct {
	Admin      string `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	CampaignId uint64 `protobuf:"varint,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
}

func (m *MsgCancelCampaign) Reset()         { *m = MsgCancelCampaign{} }
func (m *MsgCancelCampaign) String() string { return proto.CompactTextString(m) }
func (*MsgCancelCampaign) ProtoMessage()    {}
func (*MsgCancelCampaign) Descriptor() ([]byte, []int) {
	return fileDescriptor_1130ead32fd7b82c, []int{6}
}
func (m *MsgCancelCampaign) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelCampaign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelCampaign.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelCampaign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelCampaign.Merge(m, src)
}
func (m *MsgCancelCampaign) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelCampaign) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelCampaign.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelCampaign proto.InternalMessageInfo

type MsgCancelCampaignResponse struct {
	Refunded github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=refunded,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"refunded"`
}

func (m *MsgCancelCampaignResponse) Reset()         { *m = MsgCancelCampaignResponse{} }
func (m *MsgCancelCampaignResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCancelCampaignResponse) ProtoMessage()    {}
func (*MsgCancelCampaignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1130ead32fd7b82c, []int{7}
}
func (m *MsgCancelCampaignResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelCampaignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelCampaignResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelCampaignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelCampaignResponse.Merge(m, src)
}
func (m *MsgCancelCampaignResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelCampaignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelCampaignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelCampaignResponse proto.InternalMessageInfo

func (m *MsgCancelCampaignResponse) GetRefunded() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Refunded
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgRegisterRewardDenom)(nil), "do.validatorrewards.v1beta1.MsgRegisterRewardDenom")
	proto.RegisterType((*MsgRegisterRewardDenomResponse)(nil), "do.validatorrewards.v1beta1.MsgRegisterRewardDenomResponse")
	proto.RegisterType((*MsgCreateCampaign)(nil), "do.validatorrewards.v1beta1.MsgCreateCampaign")
	proto.RegisterType((*MsgCreateCampaignResponse)(nil), "do.validatorrewards.v1beta1.MsgCreateCampaignResponse")
	proto.RegisterType((*MsgReleaseCampaign)(nil), "do.validatorrewards.v1beta1.MsgReleaseCampaign")
	proto.RegisterType((*MsgReleaseCampaignResponse)(nil), "do.validatorrewards.v1beta1.MsgReleaseCampaignResponse")
	proto.RegisterType((*MsgCancelCampaign)(nil), "do.validatorrewards.v1beta1.MsgCancelCampaign")
	proto.RegisterType((*MsgCancelCampaignResponse)(nil), "do.validatorrewards.v1beta1.MsgCancelCampaignResponse")
}

func init() {
	proto.RegisterFile("do/validatorrewards/v1beta1/tx.proto", fileDescriptor_1130ead32fd7b82c)
}

var fileDescriptor_1130ead32fd7b82c = []byte{
	// 731 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0x8e, 0x9b, 0xa4, 0x6f, 0xbb, 0x79, 0xd5, 0x0a, 0x13, 0x8a, 0x1b, 0x84, 0x13, 0x2c, 0x24,
	0x02, 0x52, 0xed, 0x7e, 0xa9, 0x48, 0x85, 0x03, 0x4d, 0x7b, 0x80, 0x43, 0x85, 0x64, 0x24, 0x84,
	0x7a, 0x89, 0x36, 0xde, 0xc5, 0x59, 0xe1, 0xec, 0x46, 0xbb, 0xdb, 0x90, 0x88, 0x0b, 0xaa, 0x90,
	0xe0, 0xc8, 0x4f, 0xe8, 0x99, 0x03, 0xe2, 0xc0, 0x8f, 0xe8, 0xb1, 0xe2, 0xc4, 0x09, 0x50, 0x7b,
	0x00, 0xf1, 0x2b, 0x90, 0xbd, 0x8e, 0xf3, 0xd1, 0xd0, 0xb4, 0xe5, 0xb4, 0x99, 0x99, 0x67, 0x9e,
	0x99, 0x67, 0x67, 0xb2, 0x06, 0x37, 0x11, 0x73, 0x5a, 0x30, 0x20, 0x08, 0x4a, 0xc6, 0x39, 0x7e,
	0x09, 0x39, 0x12, 0x4e, 0x6b, 0xa9, 0x86, 0x25, 0x5c, 0x72, 0x64, 0xdb, 0x6e, 0x72, 0x26, 0x99,
	0x7e, 0x0d, 0x31, 0x7b, 0x18, 0x65, 0xc7, 0xa8, 0xc2, 0x55, 0x8f, 0x89, 0x06, 0x13, 0x4e, 0x43,
	0xf8, 0x4e, 0x6b, 0x29, 0x3c, 0x54, 0x56, 0xc1, 0x8c, 0x03, 0x35, 0x28, 0x70, 0xc2, 0xe9, 0x31,
	0x42, 0xe3, 0xf8, 0xbc, 0x8a, 0x57, 0x23, 0xcb, 0x51, 0x46, 0x1c, 0xba, 0x7d, 0x5a, 0x5b, 0xdd,
	0x06, 0x14, 0x34, 0xef, 0x33, 0x9f, 0x29, 0x8a, 0xf0, 0x97, 0xf2, 0x5a, 0x1f, 0x35, 0x30, 0xb7,
	0x2d, 0x7c, 0x17, 0xfb, 0x44, 0x48, 0xcc, 0xdd, 0x28, 0x65, 0x0b, 0x53, 0xd6, 0xd0, 0xd7, 0xc0,
	0x34, 0xdc, 0x95, 0x75, 0xc6, 0x89, 0xec, 0x18, 0x5a, 0x49, 0x2b, 0x4f, 0x57, 0x8c, 0x2f, 0x9f,
	0x17, 0xf2, 0x71, 0x03, 0x1b, 0x08, 0x71, 0x2c, 0xc4, 0x13, 0xc9, 0x09, 0xf5, 0xdd, 0x1e, 0x54,
	0xcf, 0x83, 0x2c, 0x0a, 0x09, 0x8c, 0x89, 0x30, 0xc7, 0x55, 0x86, 0x6e, 0x83, 0x2c, 0x44, 0x0d,
	0x42, 0x8d, 0xf4, 0x18, 0x26, 0x05, 0x5b, 0x9f, 0x7b, 0xb7, 0x5f, 0x4c, 0xfd, 0xda, 0x2f, 0xa6,
	0xf6, 0x7e, 0x7e, 0xba, 0xd3, 0x63, 0xb7, 0x4a, 0xc0, 0x1c, 0xdd, 0xaf, 0x8b, 0x45, 0x93, 0x51,
	0x81, 0xad, 0xdf, 0x13, 0xe0, 0xd2, 0xb6, 0xf0, 0x37, 0x39, 0x86, 0x12, 0x6f, 0xc2, 0x46, 0x13,
	0x12, 0x9f, 0xf6, 0xea, 0x6b, 0x67, 0xaa, 0xff, 0x17, 0x15, 0x79, 0x90, 0x95, 0x44, 0x06, 0x58,
	0xa9, 0x70, 0x95, 0xa1, 0x97, 0x40, 0x0e, 0x61, 0xe1, 0x71, 0xd2, 0x94, 0x84, 0x51, 0x23, 0x13,
	0xc5, 0xfa, 0x5d, 0xfa, 0x33, 0x90, 0x83, 0x41, 0xc0, 0x3c, 0x18, 0x5a, 0xc2, 0xc8, 0x96, 0xd2,
	0xe5, 0xdc, 0xf2, 0xa2, 0x7d, 0xca, 0xba, 0xd8, 0x4f, 0xbb, 0x81, 0x8d, 0x24, 0xb1, 0x92, 0x39,
	0xf8, 0x56, 0x4c, 0xb9, 0xfd, 0x54, 0xfa, 0x0d, 0xf0, 0xbf, 0x90, 0x90, 0xcb, 0x6a, 0x1d, 0x13,
	0xbf, 0x2e, 0x8d, 0xc9, 0x92, 0x56, 0x4e, 0xbb, 0xb9, 0xc8, 0xf7, 0x30, 0x72, 0xe9, 0xd7, 0x01,
	0xc0, 0x14, 0x75, 0x01, 0xff, 0x45, 0x80, 0x69, 0x4c, 0x51, 0x1c, 0xbe, 0x05, 0x66, 0x11, 0x0e,
	0xb0, 0x1f, 0xd6, 0x12, 0x55, 0x46, 0x83, 0x8e, 0x31, 0x55, 0xd2, 0xca, 0x53, 0xee, 0x4c, 0xcf,
	0xfd, 0x98, 0x06, 0x9d, 0x75, 0xbd, 0x7f, 0x24, 0xea, 0x9a, 0xac, 0xfb, 0x60, 0xfe, 0xc4, 0x5d,
	0x77, 0x27, 0xa1, 0x17, 0x41, 0xce, 0x8b, 0x7d, 0x55, 0x82, 0xa2, 0x9b, 0xcf, 0xb8, 0xa0, 0xeb,
	0x7a, 0x84, 0xac, 0x3d, 0x0d, 0xe8, 0xd1, 0x34, 0x03, 0x0c, 0x45, 0x6f, 0x56, 0xab, 0x60, 0x8a,
	0x2b, 0x17, 0x1f, 0x3b, 0xae, 0x04, 0x39, 0x5c, 0x6d, 0x62, 0xb8, 0xda, 0xfa, 0x95, 0xfe, 0xfe,
	0x93, 0x3c, 0xab, 0x09, 0x0a, 0x27, 0x7b, 0x48, 0x34, 0xb8, 0x49, 0x2f, 0xa1, 0x80, 0x7f, 0x19,
	0x5b, 0xc2, 0x63, 0xb5, 0xd5, 0x82, 0x42, 0xea, 0xe1, 0xe0, 0xc2, 0x0b, 0x3a, 0x56, 0xee, 0xa8,
	0x71, 0xbd, 0xd1, 0xd4, 0xbc, 0x06, 0x4a, 0x27, 0x5a, 0xfd, 0x50, 0xeb, 0xf3, 0x5d, 0x8a, 0x12,
	0xad, 0xf3, 0x76, 0xdc, 0x42, 0xf8, 0x36, 0x25, 0x1a, 0x37, 0x19, 0xa1, 0x95, 0xc5, 0x50, 0xd4,
	0x87, 0xef, 0xc5, 0xb2, 0x4f, 0x64, 0x7d, 0xb7, 0x66, 0x7b, 0xac, 0x11, 0xbf, 0x4d, 0xf1, 0xb1,
	0x20, 0xd0, 0x0b, 0x47, 0x76, 0x9a, 0x58, 0x44, 0x09, 0xc2, 0x4d, 0xc8, 0x97, 0x5f, 0x67, 0x40,
	0x7a, 0x5b, 0xf8, 0xfa, 0x5b, 0x0d, 0x5c, 0x1e, 0xf5, 0xf4, 0xac, 0x9c, 0x7a, 0xc5, 0xa3, 0xff,
	0xff, 0x85, 0x7b, 0x17, 0x48, 0x4a, 0xa4, 0xb7, 0xc1, 0xcc, 0xf0, 0x83, 0x31, 0x8e, 0x6e, 0x10,
	0x5f, 0x58, 0x3b, 0x1f, 0x3e, 0xa9, 0xfc, 0x0a, 0xcc, 0x0e, 0xef, 0xbf, 0x33, 0x5e, 0xc9, 0x40,
	0x42, 0xe1, 0xee, 0x39, 0x13, 0x06, 0x64, 0x0f, 0xad, 0xe1, 0x58, 0x19, 0x03, 0xf8, 0x33, 0xc8,
	0x1e, 0xb9, 0x6b, 0x95, 0x9d, 0x83, 0x23, 0x53, 0x3b, 0x3c, 0x32, 0xb5, 0x1f, 0x47, 0xa6, 0xf6,
	0xfe, 0xd8, 0x4c, 0x1d, 0x1e, 0x9b, 0xa9, 0xaf, 0xc7, 0x66, 0x6a, 0xe7, 0x41, 0xdf, 0x42, 0x6d,
	0xc1, 0x16, 0x41, 0x88, 0x79, 0x75, 0x48, 0xa8, 0x13, 0x9f, 0x0b, 0x1e, 0xe3, 0xd8, 0x69, 0xad,
	0x3a, 0xed, 0x93, 0x9f, 0xbe, 0x68, 0xdd, 0x6a, 0x93, 0xd1, 0xb7, 0x6d, 0xe5, 0x4f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x12, 0xb0, 0x22, 0xc7, 0xb5, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// RegisterRewardDenom registers or updates the admin allowed to create
	// campaigns for a reward denom. It is intended for governance execution.
	RegisterRewardDenom(ctx context.Context, in *MsgRegisterRewardDenom, opts ...grpc.CallOption) (*MsgRegisterRewardDenomResponse, error)
	// CreateCampaign funds a validator reward campaign for one or more validators.
	CreateCampaign(ctx context.Context, in *MsgCreateCampaign, opts ...grpc.CallOption) (*MsgCreateCampaignResponse, error)
	// ReleaseCampaign releases vested campaign rewards into x/distribution.
	ReleaseCampaign(ctx context.Context, in *MsgReleaseCampaign, opts ...grpc.CallOption) (*MsgReleaseCampaignResponse, error)
	// CancelCampaign refunds unreleased campaign rewards to the campaign admin.
	CancelCampaign(ctx context.Context, in *MsgCancelCampaign, opts ...grpc.CallOption) (*MsgCancelCampaignResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterRewardDenom(ctx context.Context, in *MsgRegisterRewardDenom, opts ...grpc.CallOption) (*MsgRegisterRewardDenomResponse, error) {
	out := new(MsgRegisterRewardDenomResponse)
	err := c.cc.Invoke(ctx, "/do.validatorrewards.v1beta1.Msg/RegisterRewardDenom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateCampaign(ctx context.Context, in *MsgCreateCampaign, opts ...grpc.CallOption) (*MsgCreateCampaignResponse, error) {
	out := new(MsgCreateCampaignResponse)
	err := c.cc.Invoke(ctx, "/do.validatorrewards.v1beta1.Msg/CreateCampaign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ReleaseCampaign(ctx context.Context, in *MsgReleaseCampaign, opts ...grpc.CallOption) (*MsgReleaseCampaignResponse, error) {
	out := new(MsgReleaseCampaignResponse)
	err := c.cc.Invoke(ctx, "/do.validatorrewards.v1beta1.Msg/ReleaseCampaign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CancelCampaign(ctx context.Context, in *MsgCancelCampaign, opts ...grpc.CallOption) (*MsgCancelCampaignResponse, error) {
	out := new(MsgCancelCampaignResponse)
	err := c.cc.Invoke(ctx, "/do.validatorrewards.v1beta1.Msg/CancelCampaign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// RegisterRewardDenom registers or updates the admin allowed to create
	// campaigns for a reward denom. It is intended for governance execution.
	RegisterRewardDenom(context.Context, *MsgRegisterRewardDenom) (*MsgRegisterRewardDenomResponse, error)
	// CreateCampaign funds a validator reward campaign for one or more validators.
	CreateCampaign(context.Context, *MsgCreateCampaign) (*MsgCreateCampaignResponse, error)
	// ReleaseCampaign releases vested campaign rewards into x/distribution.
	ReleaseCampaign(context.Context, *MsgReleaseCampaign) (*MsgReleaseCampaignResponse, error)
	// CancelCampaign refunds unreleased campaign rewards to the campaign admin.
	CancelCampaign(context.Context, *MsgCancelCampaign) (*MsgCancelCampaignResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterRewardDenom(ctx context.Context, req *MsgRegisterRewardDenom) (*MsgRegisterRewardDenomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterRewardDenom not implemented")
}
func (*UnimplementedMsgServer) CreateCampaign(ctx context.Context, req *MsgCreateCampaign) (*MsgCreateCampaignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCampaign not implemented")
}
func (*UnimplementedMsgServer) ReleaseCampaign(ctx context.Context, req *MsgReleaseCampaign) (*MsgReleaseCampaignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseCampaign not implemented")
}
func (*UnimplementedMsgServer) CancelCampaign(ctx context.Context, req *MsgCancelCampaign) (*MsgCancelCampaignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelCampaign not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterRewardDenom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterRewardDenom)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterRewardDenom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/do.validatorrewards.v1beta1.Msg/RegisterRewardDenom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterRewardDenom(ctx, req.(*MsgRegisterRewardDenom))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateCampaign)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/do.validatorrewards.v1beta1.Msg/CreateCampaign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateCampaign(ctx, req.(*MsgCreateCampaign))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ReleaseCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgReleaseCampaign)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ReleaseCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/do.validatorrewards.v1beta1.Msg/ReleaseCampaign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ReleaseCampaign(ctx, req.(*MsgReleaseCampaign))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CancelCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCancelCampaign)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CancelCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/do.validatorrewards.v1beta1.Msg/CancelCampaign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CancelCampaign(ctx, req.(*MsgCancelCampaign))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "do.validatorrewards.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterRewardDenom",
			Handler:    _Msg_RegisterRewardDenom_Handler,
		},
		{
			MethodName: "CreateCampaign",
			Handler:    _Msg_CreateCampaign_Handler,
		},
		{
			MethodName: "ReleaseCampaign",
			Handler:    _Msg_ReleaseCampaign_Handler,
		},
		{
			MethodName: "CancelCampaign",
			Handler:    _Msg_CancelCampaign_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "do/validatorrewards/v1beta1/tx.proto",
}

func (m *MsgRegisterRewardDenom) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterRewardDenom) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterRewardDenom) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterRewardDenomResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterRewardDenomResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterRewardDenomResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateCampaign) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateCampaign) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateCampaign) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DelegatorsOnly {
		i--
		if m.DelegatorsOnly {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.EndHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EndHeight))
		i--
		dAtA[i] = 0x38
	}
	if m.StartHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.StartHeight))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Allocations) > 0 {
		for iNdEx := len(m.Allocations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Allocations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateCampaignResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateCampaignResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateCampaignResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CampaignId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.CampaignId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgReleaseCampaign) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgReleaseCampaign) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgReleaseCampaign) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CampaignId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.CampaignId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Releaser) > 0 {
		i -= len(m.Releaser)
		copy(dAtA[i:], m.Releaser)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Releaser)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgReleaseCampaignResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgReleaseCampaignResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgReleaseCampaignResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Released) > 0 {
		for iNdEx := len(m.Released) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Released[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *MsgCancelCampaign) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelCampaign) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelCampaign) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CampaignId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.CampaignId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCancelCampaignResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelCampaignResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelCampaignResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Refunded) > 0 {
		for iNdEx := len(m.Refunded) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Refunded[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterRewardDenom) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterRewardDenomResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateCampaign) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Allocations) > 0 {
		for _, e := range m.Allocations {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if m.StartHeight != 0 {
		n += 1 + sovTx(uint64(m.StartHeight))
	}
	if m.EndHeight != 0 {
		n += 1 + sovTx(uint64(m.EndHeight))
	}
	if m.DelegatorsOnly {
		n += 2
	}
	return n
}

func (m *MsgCreateCampaignResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CampaignId != 0 {
		n += 1 + sovTx(uint64(m.CampaignId))
	}
	return n
}

func (m *MsgReleaseCampaign) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Releaser)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.CampaignId != 0 {
		n += 1 + sovTx(uint64(m.CampaignId))
	}
	return n
}

func (m *MsgReleaseCampaignResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Released) > 0 {
		for _, e := range m.Released {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgCancelCampaign) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.CampaignId != 0 {
		n += 1 + sovTx(uint64(m.CampaignId))
	}
	return n
}

func (m *MsgCancelCampaignResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Refunded) > 0 {
		for _, e := range m.Refunded {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterRewardDenom) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterRewardDenom: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterRewardDenom: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterRewardDenomResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterRewardDenomResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterRewardDenomResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateCampaign) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateCampaign: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateCampaign: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Allocations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Allocations = append(m.Allocations, ValidatorAllocation{})
			if err := m.Allocations[len(m.Allocations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartHeight", wireType)
			}
			m.StartHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndHeight", wireType)
			}
			m.EndHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegatorsOnly", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DelegatorsOnly = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateCampaignResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateCampaignResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateCampaignResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CampaignId", wireType)
			}
			m.CampaignId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CampaignId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgReleaseCampaign) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgReleaseCampaign: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgReleaseCampaign: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Releaser", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Releaser = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CampaignId", wireType)
			}
			m.CampaignId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CampaignId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgReleaseCampaignResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgReleaseCampaignResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgReleaseCampaignResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Released", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Released = append(m.Released, ValidatorAllocation{})
			if err := m.Released[len(m.Released)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelCampaign) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelCampaign: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelCampaign: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CampaignId", wireType)
			}
			m.CampaignId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CampaignId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelCampaignResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelCampaignResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelCampaignResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Refunded", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Refunded = append(m.Refunded, types.Coin{})
			if err := m.Refunded[len(m.Refunded)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
