// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: do/dodxstaking/v1beta1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines x/dodxstaking genesis state.
type GenesisState struct {
	Stakes             []StakeRecord               `protobuf:"bytes,1,rep,name=stakes,proto3" json:"stakes"`
	GovernanceEnabled  bool                        `protobuf:"varint,2,opt,name=governance_enabled,json=governanceEnabled,proto3" json:"governance_enabled,omitempty"`
	RewardAccumulators []RewardAmountRecord        `protobuf:"bytes,3,rep,name=reward_accumulators,json=rewardAccumulators,proto3" json:"reward_accumulators"`
	RewardPools        []RewardAmountRecord        `protobuf:"bytes,4,rep,name=reward_pools,json=rewardPools,proto3" json:"reward_pools"`
	RewardDebts        []AccountRewardAmountRecord `protobuf:"bytes,5,rep,name=reward_debts,json=rewardDebts,proto3" json:"reward_debts"`
	PendingRewards     []AccountRewardAmountRecord `protobuf:"bytes,6,rep,name=pending_rewards,json=pendingRewards,proto3" json:"pending_rewards"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce65c580d63d6bc8, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetStakes() []StakeRecord {
	if m != nil {
		return m.Stakes
	}
	return nil
}

func (m *GenesisState) GetGovernanceEnabled() bool {
	if m != nil {
		return m.GovernanceEnabled
	}
	return false
}

func (m *GenesisState) GetRewardAccumulators() []RewardAmountRecord {
	if m != nil {
		return m.RewardAccumulators
	}
	return nil
}

func (m *GenesisState) GetRewardPools() []RewardAmountRecord {
	if m != nil {
		return m.RewardPools
	}
	return nil
}

func (m *GenesisState) GetRewardDebts() []AccountRewardAmountRecord {
	if m != nil {
		return m.RewardDebts
	}
	return nil
}

func (m *GenesisState) GetPendingRewards() []AccountRewardAmountRecord {
	if m != nil {
		return m.PendingRewards
	}
	return nil
}

// RewardAmountRecord stores module-level reward accounting values.
type RewardAmountRecord struct {
	Denom  string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *RewardAmountRecord) Reset()         { *m = RewardAmountRecord{} }
func (m *RewardAmountRecord) String() string { return proto.CompactTextString(m) }
func (*RewardAmountRecord) ProtoMessage()    {}
func (*RewardAmountRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce65c580d63d6bc8, []int{1}
}
func (m *RewardAmountRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RewardAmountRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RewardAmountRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RewardAmountRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewardAmountRecord.Merge(m, src)
}
func (m *RewardAmountRecord) XXX_Size() int {
	return m.Size()
}
func (m *RewardAmountRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_RewardAmountRecord.DiscardUnknown(m)
}

var xxx_messageInfo_RewardAmountRecord proto.InternalMessageInfo

func (m *RewardAmountRecord) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *RewardAmountRecord) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

// AccountRewardAmountRecord stores per-account reward accounting values.
type AccountRewardAmountRecord struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Denom   string `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount  string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *AccountRewardAmountRecord) Reset()         { *m = AccountRewardAmountRecord{} }
func (m *AccountRewardAmountRecord) String() string { return proto.CompactTextString(m) }
func (*AccountRewardAmountRecord) ProtoMessage()    {}
func (*AccountRewardAmountRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce65c580d63d6bc8, []int{2}
}
func (m *AccountRewardAmountRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountRewardAmountRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountRewardAmountRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountRewardAmountRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRewardAmountRecord.Merge(m, src)
}
func (m *AccountRewardAmountRecord) XXX_Size() int {
	return m.Size()
}
func (m *AccountRewardAmountRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRewardAmountRecord.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRewardAmountRecord proto.InternalMessageInfo

func (m *AccountRewardAmountRecord) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AccountRewardAmountRecord) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *AccountRewardAmountRecord) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "do.dodxstaking.v1beta1.GenesisState")
	proto.RegisterType((*RewardAmountRecord)(nil), "do.dodxstaking.v1beta1.RewardAmountRecord")
	proto.RegisterType((*AccountRewardAmountRecord)(nil), "do.dodxstaking.v1beta1.AccountRewardAmountRecord")
}

func init() {
	proto.RegisterFile("do/dodxstaking/v1beta1/genesis.proto", fileDescriptor_ce65c580d63d6bc8)
}

var fileDescriptor_ce65c580d63d6bc8 = []byte{
	// 455 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xe3, 0xa6, 0x0d, 0x74, 0x5b, 0x81, 0x58, 0xa2, 0xca, 0xed, 0xc1, 0x44, 0x81, 0x43,
	0x84, 0x14, 0x5b, 0x29, 0xdc, 0x38, 0x39, 0x2a, 0xe2, 0x8a, 0x1c, 0x71, 0xe9, 0x25, 0xac, 0x77,
	0x47, 0xae, 0x45, 0xbc, 0x13, 0xed, 0x6e, 0x42, 0x39, 0xf0, 0x0e, 0x3c, 0x0c, 0x0f, 0xd1, 0x63,
	0xc5, 0x89, 0x13, 0x42, 0xc9, 0x3b, 0x70, 0x46, 0xde, 0x5d, 0x68, 0x2a, 0x62, 0x0e, 0x70, 0xb2,
	0xff, 0x99, 0x7f, 0xbe, 0x7f, 0x24, 0x7b, 0xc8, 0x13, 0x81, 0x89, 0x40, 0x71, 0xa9, 0x0d, 0x7b,
	0x57, 0xca, 0x22, 0x59, 0x8e, 0x72, 0x30, 0x6c, 0x94, 0x14, 0x20, 0x41, 0x97, 0x3a, 0x9e, 0x2b,
	0x34, 0x48, 0x8f, 0x04, 0xc6, 0x1b, 0xae, 0xd8, 0xbb, 0x4e, 0xfa, 0x0d, 0xd3, 0xb5, 0x06, 0x37,
	0x7b, 0x72, 0xcc, 0x51, 0x57, 0xa8, 0xa7, 0x56, 0x25, 0x4e, 0xf8, 0x56, 0xb7, 0xc0, 0x02, 0x5d,
	0xbd, 0x7e, 0x73, 0xd5, 0xfe, 0x8f, 0x36, 0x39, 0x7c, 0xe5, 0xe2, 0x27, 0x86, 0x19, 0xa0, 0x29,
	0xe9, 0x58, 0xa0, 0x0e, 0x83, 0x5e, 0x7b, 0x70, 0x70, 0xfa, 0x38, 0xde, 0xbe, 0x4e, 0x3c, 0xa9,
	0x5d, 0x19, 0x70, 0x54, 0x62, 0xbc, 0x7b, 0xf5, 0xed, 0x51, 0x2b, 0xf3, 0x83, 0x74, 0x48, 0x68,
	0x81, 0x4b, 0x50, 0x92, 0x49, 0x0e, 0x53, 0x90, 0x2c, 0x9f, 0x81, 0x08, 0x77, 0x7a, 0xc1, 0xe0,
	0x6e, 0xf6, 0xe0, 0xa6, 0xf3, 0xd2, 0x35, 0x28, 0x23, 0x0f, 0x15, 0xbc, 0x67, 0x4a, 0x4c, 0x19,
	0xe7, 0x8b, 0x6a, 0x31, 0x63, 0x06, 0x95, 0x0e, 0xdb, 0x36, 0xfe, 0x69, 0x53, 0x7c, 0x66, 0x47,
	0xd2, 0x0a, 0x17, 0xd2, 0xdc, 0xda, 0x82, 0x3a, 0x58, 0xba, 0xc1, 0xa2, 0x13, 0x72, 0xe8, 0x23,
	0xe6, 0x88, 0x33, 0x1d, 0xee, 0xfe, 0x23, 0xfb, 0xc0, 0x51, 0x5e, 0xd7, 0x10, 0x7a, 0xfe, 0x1b,
	0x2a, 0x20, 0x37, 0x3a, 0xdc, 0xb3, 0xd0, 0x51, 0x13, 0x34, 0xe5, 0xdc, 0xf1, 0xfe, 0xce, 0x3e,
	0xab, 0x59, 0xf4, 0x2d, 0xb9, 0x3f, 0x07, 0x29, 0x4a, 0x59, 0x4c, 0x5d, 0x59, 0x87, 0x9d, 0xff,
	0xc3, 0xdf, 0xf3, 0x3c, 0x67, 0xd0, 0xfd, 0x31, 0xa1, 0x7f, 0x7a, 0x69, 0x97, 0xec, 0x09, 0x90,
	0x58, 0x85, 0x41, 0x2f, 0x18, 0xec, 0x67, 0x4e, 0xd0, 0x23, 0xd2, 0x61, 0xd6, 0x65, 0x3f, 0xe2,
	0x7e, 0xe6, 0x55, 0xff, 0x23, 0x39, 0x6e, 0x8c, 0xa5, 0xa7, 0xe4, 0x0e, 0x13, 0x42, 0x81, 0xd6,
	0x0e, 0x36, 0x0e, 0xbf, 0x7c, 0x1e, 0x76, 0xfd, 0x2f, 0x99, 0xba, 0xce, 0xc4, 0xa8, 0x7a, 0xa5,
	0x5f, 0xc6, 0x9b, 0xf8, 0x9d, 0xed, 0xf1, 0xed, 0xcd, 0xf8, 0xf1, 0x9b, 0xab, 0x55, 0x14, 0x5c,
	0xaf, 0xa2, 0xe0, 0xfb, 0x2a, 0x0a, 0x3e, 0xad, 0xa3, 0xd6, 0xf5, 0x3a, 0x6a, 0x7d, 0x5d, 0x47,
	0xad, 0xf3, 0x17, 0x45, 0x69, 0x2e, 0x16, 0x79, 0xcc, 0xb1, 0x4a, 0xce, 0xd8, 0xb2, 0x14, 0x02,
	0xf9, 0x05, 0x2b, 0x65, 0xe2, 0x9f, 0x43, 0x8e, 0x0a, 0x92, 0xe5, 0xf3, 0xe4, 0xf2, 0xd6, 0x45,
	0x99, 0x0f, 0x73, 0xd0, 0x79, 0xc7, 0x5e, 0xc6, 0xb3, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7b,
	0x30, 0xb0, 0x27, 0xae, 0x03, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PendingRewards) > 0 {
		for iNdEx := len(m.PendingRewards) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingRewards[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.RewardDebts) > 0 {
		for iNdEx := len(m.RewardDebts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RewardDebts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.RewardPools) > 0 {
		for iNdEx := len(m.RewardPools) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RewardPools[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.RewardAccumulators) > 0 {
		for iNdEx := len(m.RewardAccumulators) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RewardAccumulators[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.GovernanceEnabled {
		i--
		if m.GovernanceEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.Stakes) > 0 {
		for iNdEx := len(m.Stakes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Stakes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *RewardAmountRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RewardAmountRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RewardAmountRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AccountRewardAmountRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountRewardAmountRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccountRewardAmountRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Stakes) > 0 {
		for _, e := range m.Stakes {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.GovernanceEnabled {
		n += 2
	}
	if len(m.RewardAccumulators) > 0 {
		for _, e := range m.RewardAccumulators {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RewardPools) > 0 {
		for _, e := range m.RewardPools {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RewardDebts) > 0 {
		for _, e := range m.RewardDebts {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PendingRewards) > 0 {
		for _, e := range m.PendingRewards {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *RewardAmountRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func (m *AccountRewardAmountRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stakes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Stakes = append(m.Stakes, StakeRecord{})
			if err := m.Stakes[len(m.Stakes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GovernanceEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.GovernanceEnabled = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardAccumulators", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardAccumulators = append(m.RewardAccumulators, RewardAmountRecord{})
			if err := m.RewardAccumulators[len(m.RewardAccumulators)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardPools", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardPools = append(m.RewardPools, RewardAmountRecord{})
			if err := m.RewardPools[len(m.RewardPools)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardDebts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardDebts = append(m.RewardDebts, AccountRewardAmountRecord{})
			if err := m.RewardDebts[len(m.RewardDebts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingRewards", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingRewards = append(m.PendingRewards, AccountRewardAmountRecord{})
			if err := m.PendingRewards[len(m.PendingRewards)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RewardAmountRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RewardAmountRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RewardAmountRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AccountRewardAmountRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountRewardAmountRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountRewardAmountRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
