name: Lint
on:
  push:
    branches:
      - main
      - release/**
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25.12"
          check-latest: true
      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            **/*.go
            go.mod
            go.sum
            **/go.mod
            **/go.sum
      - name: run linting
        if: env.GIT_DIFF || startsWith(github.ref, 'refs/heads/release/')
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            make lint
          else
            make lint-new LINT_BASE_REV=origin/main
          fi





